server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
#        - id: shop-picture-service
#          uri: lb://SHOP-PICTURE-SERVICE
#          predicates:
#            - Path=/api/v1/picture/**
        - id: shop_backend_api
          uri: lb://SHOP_BACKEND_API
          predicates:
            - Path=/api/v1/**
